trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildAndPublishOdooModule
    steps:
    - checkout: self

    # Copy files to artifacts directory
    - task: CopyFiles@2
      inputs:
        sourceFolder: 'addons/indika_module'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
        ArtifactName: 'copiedindikamodule-artifact'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'

- stage: DeployToLocalMachine
  displayName: 'Deploy to Local Machine'
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'local env'  # Replace with the name of your environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'copiedindikamodule-artifact'
            # path: '$(Pipeline.Workspace)/OdooModuleArtifacts'

          - script: |
              mkdir -p $HOME/deployodoo/
              cp -r $(Pipeline.Workspace)/copiedindikamodule-artifact/* $HOME/deployodoo/
            displayName: 'Move files to local machine path'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello world'
