trigger:
- '*'  

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployOdooModule
  steps:
  - checkout: self

  # Copy files to artifacts directory
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'addons/indika_module'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

  # Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
       ArtifactName: 'copiedindikamodule-artifact'
       publishLocation: 'Container'
    displayName: 'Publish Artifact'

# Add a new job to download the artifacts and move them to the desired local machine path
- job: DownloadArtifactsAnddeploytolocalmachine
  displayName:  DeployOdooModule
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - download: current
    artifact: 'copiedindikamodule-artifact'
    # path: $(Pipeline.Workspace)/OdooModuleArtifacts

  - script: |
      cp $(Pipeline.Workspace)/copiedindikamodule-artifact/* /users/shaikfahemida/odoo/odoo/addons/indika_module/
    displayName: 'Move files to local machine path'

