# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Or your preferred branch

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - checkout: self

  - script: |
      # Set up your environment, install dependencies, etc.
      # For example, install Odoo dependencies.
      sudo apt-get install -y python3-pip
      pip3 install -r requirements.txt
    displayName: 'Set up Environment'

  - script: |
      # Build your Indika module
      # For example, package it as a ZIP file.
      zip -r indika_module.zip indika_module/*
    displayName: 'Build Indika Module'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)'
      ArtifactName: 'indika-artifact'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'
