trigger:
- '*'

pr:
- '*'

pool:
  name: myagentpool

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildAndPublishOdooModule
    steps:
    - checkout: self

    # Copy files to artifacts directory
    - task: CopyFiles@2
      inputs:
        sourceFolder: 'addons/indika_module'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
        ArtifactName: 'copiedindikamodule-artifact'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'copiedindikamodule-artifact'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CmdLine@2
      inputs:
        script: |
          echo Hello world
    - task: CmdLine@2
      
      inputs:
        script: |
          echo welcome to choose Os System and then copy files
          if [ "$(Agent.OS)" == "Linux" ] || [ "$(Agent.OS)" == "Darwin" ]; then
          # macOS/Linux specific commands
          pwd
          echo welcome to the Mac Os system
          cp -r $(System.ArtifactsDirectory)/copiedindikamodule-artifact/* $HOME/odoo/odoo/addons/indika_module/
          else [ "$(Agent.OS)" == "Windows_NT" ]; then
            echo "welcome to the Windows Os system"
            xcopy /E /Y "$(System.ArtifactsDirectory)\copiedindikamodule-artifact\*" "%HOMEPATH%\odoo\odoo\addons\indika_module\"
          
      