trigger:
- '*'  

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployOdooModule
  steps:
  - checkout: self

  # Copy files to artifacts directory
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'addons/indika_module'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

  # Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
       ArtifactName: 'OdooModuleArtifacts'
       publishLocation: 'Container'
    displayName: 'Publish Artifact'
  # - task: DownloadPipelineArtifact@2
  #   inputs:
  #     buildType: 'specific'
  #     project: '0a1a54f4-4331-40d0-9838-837827b7653e'
  #     definition: '1'
  #     buildVersionToDownload: 'latest'
  #     artifactName: 'OdooModuleArtifacts'
  #     targetPath: '$(Pipeline.Workspace)/OdooModuleArtifacts'
# # Add a new job to download the artifacts and move them to the desired local machine path
# - job: DownloadArtifactsAnddeploytolocalmachine
#   displayName:  DeployOdooModule
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - download: current
#     artifact: 'copiedindikamodule-artifact'
#     # path: $(Pipeline.Workspace)/OdooModuleArtifacts

  - script: |
      mkdir -p $HOME/deployodoo/
      cp -r $(Pipeline.Workspace)/OdooModuleArtifacts/* $HOME/deployodoo/
    displayName: 'Move files to local machine path'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        - script: |
          mkdir -p $HOME/deployodoo/
          cp -r $(Pipeline.Workspace)/OdooModuleArtifacts/* $HOME/deployodoo/
    
        echo 'Hello world'

