trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildAndPublishOdooModule
    steps:
    - checkout: self

    # Copy files to artifacts directory
    - task: CopyFiles@2
      inputs:
        sourceFolder: 'addons/indika_module'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
        ArtifactName: 'copiedindikamodule-artifact'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'copiedindikamodule-artifact'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CmdLine@2
      inputs:
        script: |
          pwd
          echo Hello world
    - script: |
        mkdir -p $HOME/deployodoo/
        pwd
        cp -r $(System.ArtifactsDirectory)/copiedindikamodule-artifact/* $HOME/deployodoo/
      displayName: 'Move files to local machine path'

 