trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployOdooModule
  steps:
  - checkout: self

  # Copy files to artifacts directory
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'addons/indika_module'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

  # Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
       ArtifactName: 'copiedindikamodule-artifact'
       publishLocation: 'Container'
    displayName: 'Publish Artifact'

# # Add a new job to download the artifacts and move them to the desired local machine path
# - job: DownloadArtifactsAndMove
#   dependsOn: DeployOdooModule
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - download: current
#     artifact: OdooModuleArtifacts
#     # path: $(Pipeline.Workspace)/OdooModuleArtifacts

#   - script: |
#       mkdir -p /users/shaikfahemida/odoo/odoo/addons/indika_module1
#       mv $(Pipeline.Workspace)/OdooModuleArtifacts/indika_module/* /users/shaikfahemida/odoo/odoo/addons/indika_module1/
#     displayName: 'Move files to local machine path'

# pool:
#   vmImage: 'ubuntu-latest'

# jobs:
# - job: Build
#   steps:
#   - checkout: self

#   - script: |
#       # Set up your environment, install dependencies, etc.
#       # For example, install Odoo dependencies.
#           sudo apt-get install -y python3-pip
#           sudo apt-get install -y zip
#     displayName: 'Set up Environment'

#   - script: |
#       # Build your Indika module
#       # For example, package it as a ZIP file.
#       # zip -r indika_module.zip . -i addons/indika_module/*
#       zip -r $(Build.ArtifactStagingDirectory)/indika_module.zip . -i addons/indika_module
#     displayName: 'Build Indika Module'
    
#   - task: PublishBuildArtifacts@1
#     inputs:
#       PathtoPublish: '$(Build.SourcesDirectory)'
#       ArtifactName: 'indika-artifact'
#       publishLocation: 'Container'
#     displayName: 'Publish Artifact'
