trigger:
- '*'


pr:
- '*'

stages:
- stage: BuildWindows
  displayName: 'Build Stage - Windows'
  jobs:
  - job: BuildAndPublishOdooModuleWindows
    pool:
      name: rafiWinpool  # Specify the Windows agent pool
    steps:
    - checkout: self
    - task: CopyFiles@2
      inputs:
        sourceFolder: 'addons/indika_module'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
        ArtifactName: 'copiedindikamodule-artifact'
        publishLocation: 'Container'
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'copiedindikamodule-artifact'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CmdLine@2
      inputs:
        script: |
          echo Hello world
    - task: CmdLine@2
      inputs:
        script: |
          echo welcome to the Windows system
          mkdir odoo
          xcopy /E /Y $(System.ArtifactsDirectory)\copiedindikamodule-artifact\* %HOMEPATH%\odoo\odoo\addons\indika_module\



      