trigger:
- '*'

pr:
- '*'

pool:
  name: myagentpool

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildAndPublishOdooModule
    steps:
    - checkout: self

    # Copy files to artifacts directory
    - task: CopyFiles@2
      inputs:
        sourceFolder: 'addons/indika_module'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
        ArtifactName: 'copiedindikamodule-artifact'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'copiedindikamodule-artifact'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CmdLine@2
      inputs:
        script: |
          echo Hello world
    - script: |
        if [ "$(Agent.OS)" == "Linux" ] || [ "$(Agent.OS)" == "Darwin" ]; then
          # macOS/Linux specific commands
          pwd
          echo "welcome to the Mac Os system"
          cp -r $(System.ArtifactsDirectory)/copiedindikamodule-artifact/* $HOME/odoo/odoo/addons/indika_module/
        elif [ "$(Agent.OS)" == "Windows_NT" ]; then
          # Windows specific commands
          echo "welcome to the Windows Os system"
          # copy "$(System.ArtifactsDirectory)\copiedindikamodule-artifact\*" "%HOMEPATH%\odoo\odoo\addons\indika_module\"
          xcopy /E /Y "$(System.ArtifactsDirectory)\copiedindikamodule-artifact\*" "%HOMEPATH%\odoo\odoo\addons\indika_module\"
          # xcopy "$(System.ArtifactsDirectory)\\copiedindikamodule-artifact\\*" "%HOMEPATH%\\odoo\\odoo\\addons\\indika_module\\ " /E /Y
        else
          echo "Unsupported operating system"
          exit 1
        fi 
      displayName: 'Move files to local machine path'
 