trigger:

- main  
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployOdooModule
  steps:
  - checkout: self
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'addons/indika_module'
      contents: '**'
      targetFolder: '$HOME/odoo/odoo/addons/indika_module'  # Use a different target folder
  - task: Bash@3
    inputs:
      targetType: 'inline'
  - script: |
      echo 'Hello world'
      cd ~
      ls
      cd odoo
      cd odoo
      cd python3.8 odoo-bin --addons-path addons
  displayName: 'Copy module and restart Odoo'

# pool:
#   vmImage: 'ubuntu-latest'

# jobs:
# - job: Build
#   steps:
#   - checkout: self

#   - script: |
#       # Set up your environment, install dependencies, etc.
#       # For example, install Odoo dependencies.
#           sudo apt-get install -y python3-pip
#           sudo apt-get install -y zip
#     displayName: 'Set up Environment'

#   - script: |
#       # Build your Indika module
#       # For example, package it as a ZIP file.
#       # zip -r indika_module.zip . -i indika_module/*
#       zip -r $(Build.ArtifactStagingDirectory)/indika_module.zip . -i indika_module
#     displayName: 'Build Indika Module'
    
#   - task: PublishBuildArtifacts@1
#     inputs:
#       PathtoPublish: '$(Build.SourcesDirectory)'
#       ArtifactName: 'indika-artifact'
#       publishLocation: 'Container'
#     displayName: 'Publish Artifact'
