# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Or your preferred branch

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - checkout: self

  - script: |
      # Set up your environment, install dependencies, etc.
      # For example, install Odoo dependencies.
          sudo apt-get install -y python3-pip
    displayName: 'Set up Environment'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/addons/indika_module'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     PathtoPublish: '$(Build.SourcesDirectory)'
  #     ArtifactName: 'indika-artifact'
  #     publishLocation: 'Container'
  #   displayName: 'Publish Artifact'
