trigger:
- '*'  

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPublishOdooModule
  steps:
  - checkout: self

  # Copy files to artifacts directory
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'addons/indika_module'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)/indika_module'

  # Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)/indika_module'
       ArtifactName: 'copiedindikamodule-artifact'
       publishLocation: 'Container'
    displayName: 'Publish Artifact'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '0a1a54f4-4331-40d0-9838-837827b7653e'
    pipeline: '1'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'copiedindikamodule-artifact'
    downloadPath: '$(System.ArtifactsDirectory)'

  - script: |
      mkdir -p $HOME/deployodoo/
      cp -r $(System.ArtifactsDirectory)/copiedindikamodule-artifact/* $HOME/deployodoo/
    displayName: 'Move files to local machine path'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'Hello world'
